-- Insert mock events data
INSERT INTO events (title, description, category, venue, location, event_date, price, available_seats, image_url, created_at, updated_at) VALUES
('The Grand Symphony', 'Experience an evening of classical masterpieces performed by the renowned orchestra. This spectacular event brings together the finest musicians for an unforgettable performance in the historic Grand Theatre.', 'concert', 'Grand Theatre', 'Downtown', '2025-12-25 19:00:00', 45.00, 150, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Shakespeare in the Park', 'A timeless tale brought to life under the stars. Join us for an enchanting outdoor performance of one of Shakespeare''s greatest works.', 'theatre', 'Central Park Amphitheatre', 'Uptown', '2025-12-28 18:00:00', 30.00, 200, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Casablanca Screening', 'Step back in time with a classic screening of the beloved 1942 romantic drama. Enjoy the timeless story of love and sacrifice on the big screen.', 'cinema', 'The Roxy Cinema', 'Downtown', '2026-01-02 20:00:00', 15.00, 100, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Jazz Under the Stars', 'An evening of smooth jazz performances featuring legendary artists and rising stars. Enjoy fine wine and music under the night sky.', 'festival', 'Riverside Pavilion', 'Waterfront', '2026-01-05 21:00:00', 55.00, 300, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('The Phantom of the Opera', 'The legendary musical returns for a limited engagement. Experience the magic, mystery, and romance of this beloved classic.', 'theatre', 'Royal Opera House', 'Downtown', '2026-01-10 19:30:00', 85.00, 180, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vintage Film Festival', 'A celebration of golden age cinema featuring restored classics from the 1940s and 1950s. Multiple screenings throughout the day.', 'festival', 'Heritage Cinema', 'Old Town', '2026-01-15 14:00:00', 25.00, 250, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Piano Concerto Evening', 'Renowned pianist performs Chopin and Liszt in an intimate setting. A night of musical brilliance and emotional depth.', 'concert', 'Concert Hall', 'Arts District', '2026-01-18 20:00:00', 60.00, 120, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sunset Boulevard Screening', 'Billy Wilder''s masterpiece returns to the silver screen. A dark tale of Hollywood glamour and obsession.', 'cinema', 'The Roxy Cinema', 'Downtown', '2026-01-22 19:00:00', 18.00, 90, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
